// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDiqeb3jNyoHIlspiPvLRVvmgaNMmAT4Y',
    appId: '1:614415855678:web:022eadcc0a3c17c6b0216f',
    messagingSenderId: '614415855678',
    projectId: 'lutterm',
    authDomain: 'lutterm.firebaseapp.com',
    storageBucket: 'lutterm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0NN1mcT6rn2ALGLeuWigTorVuyxd1ik',
    appId: '1:614415855678:android:661cc6f09b556627b0216f',
    messagingSenderId: '614415855678',
    projectId: 'lutterm',
    storageBucket: 'lutterm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQpZkgUSnvXuPR0z0orWTok00fLgj7ptg',
    appId: '1:614415855678:ios:ebe211695845cb37b0216f',
    messagingSenderId: '614415855678',
    projectId: 'lutterm',
    storageBucket: 'lutterm.appspot.com',
    iosClientId: '614415855678-brkv1d5jguve7a1088o6d4spe8ddordo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttern.flutterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQpZkgUSnvXuPR0z0orWTok00fLgj7ptg',
    appId: '1:614415855678:ios:ebe211695845cb37b0216f',
    messagingSenderId: '614415855678',
    projectId: 'lutterm',
    storageBucket: 'lutterm.appspot.com',
    iosClientId: '614415855678-brkv1d5jguve7a1088o6d4spe8ddordo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttern.flutterm',
  );
}
